#!/usr/bin/env bash
# to display "To infinity and beyond" indefinitely with
#+ sleep 2 in between every iteration
#   to display "I am invincible!!!" in between every iteration

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM 
done
