#!/usr/bin/env bash
# Looping from 1 to 10
#   displays "bad luck" in the 4th iteration
#   displays  "good luck" in the 8th iteration
#   displays "Best School" for all other iterations

size = 0
while [$size -lt 10 ]
do
	if [$size =eq 3 ]
	then
		echo "bad luck"
	elif [$size -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((size++))
done
