#!/usr/bin/env bash
# to display numbers from 1 to 20
# Also:
#   "bad luck from China" for 4th iteration
#   "bad luck from Japan" for 9th iteration
#   "bad luck from Italy" for 17th iteration

size=1

while [ $size -le 20 ]
do
  echo "$size"
  case $size in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( size++ ))
done

